### ISSUE TITLE
AsyncAPI spec v3 support in Java Spring template

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/java-spring-template#308]
#### Reason/Context
This Issue is used to track changes needed to support AsyncAPI v3. As a code owner, please edit this list of TODO tasks in order to properly track the progress 🙂 Once this issue is closed it means that v3 is now fully supported in this library.  

Remaining tasks:

- [ ] Update template to use parser v2, this is already supported by the [generator by changing the `apiVersion`](https://github.com/asyncapi/generator/blob/master/docs/configuration-file.md)

**Comment by Tenischev** [comment]
I start slowly gather here tasks:

- [ ] update template to use parser-js v3. It doesn't make much sense to migrate from v1 to v2 when v2 is outdated. The problem is in significant [parser API](https://github.com/asyncapi/parser-api/blob/v3.0.0/docs/api.md) change
- [ ] support reply operation, follow to asyncapi/spec#981
- [ ] probably most of all calls to `channels()` has to be changed to `operations()` with rewrite of underling code, because for program it's more important which operations should be made instead of which channels are defined. It may be sense to use `channels()` in Configuration class.
- [ ] use `channel.address()` instead of `channelName`
- [ ] no more `hasPublish` or `hasSubscribe` methods
- [ ] operation now should work only like `oneOf` is several possible messages are listed (clarification of Parser API is required here)
- [ ] any parameters of channel now could be only `string` type (clarification of Parser API is required here)

**Comment by johnament** [comment]
Are there any plans to address this?

**Comment by snoweuph** [comment]
This is still required and important, this means that an up-to-date spec can't be used with spring, which still is quite important in industry, and people learning programming in an Apprenticeship in Germany are even required to learn it.
