### ISSUE TITLE
Please provide documentation

### ISSUE THREAD

**Issue by GreenRover** [asyncapi/java-spring-template#5]
when i run:
ag -o foo --force-write spec.yaml java-spring

I get following error:
Error: 404 Not Found - GET https://registry.npmjs.org/java-spring - Not found

As work around i cloned this directory and changed the generator.js to:
```
      //const { name: templatePkgName, path: templatePkgPath } = await this.installTemplate(this.install);
      this.templateDir = this.templateName;
      this.templateName = this.templateName;
```
This results in an empty template.
Can some one please provide a tutorial.

**Comment by derberg** [comment]
Hi @GreenRover. The docs are outdated, but as you can see in the Readme, actually the whole template is outdated, it doesn't support AsyncAPI 2.0 version.

To start generation, instead of `ag -o foo --force-write spec.yaml java-spring` you should do `ag -o foo --force-write spec.yaml @asyncapi/java-spring-template`. More options are listed here https://github.com/asyncapi/generator/#usage.
Would be awesome if you could create a PR with a suggestion on how to improve the README.md

**Comment by derberg** [comment]
@GreenRover template got updated by @Tenischev to use AsyncAPI 2.0 and using this opportunity he improved README.md a lot so I will close this one and once you notice some more issues please reopen or better just create new issue
