### ISSUE TITLE
Validation check against ReadMe MUST requirements

### ISSUE THREAD

**Issue by Tenischev** [asyncapi/java-spring-template#99]
#### Reason/Context
For the correct generation template require from AsynAPI to MUST have some parameters which is optional from spec point of view.
Currently the not-compilable code will be the result if user will ignore requirements from ReadMe.
See also #57 

#### Description
Add hook `generator:before` to check for specific parameters in AsyncAPI file.
Produce error message for the user with description what should be added to AsyncAPI.

**Comment by fmvilas** [comment]
Hey @Tenischev. What about creating a filter called `throwIfUndefined` that will throw an error if something is undefined?

You could use it in your template [here](https://github.com/asyncapi/java-spring-template/blob/master/template/src/main/java/com/asyncapi/service/MessageHandlerService.java#L41) like:

```nunjucks
    public void {{channel.publish().id() | throwIfUndefined | camelCase}}(@Payload {{channel.publish().message().payload().uid() | camelCase | upperFirst}} payload,
```

It could even take a message:

```nunjucks
    public void {{channel.publish().id() | throwIfUndefined('operationId is required for this template to work.') | camelCase}}(@Payload {{channel.publish().message().payload().uid() | camelCase | upperFirst}} payload,
```

**Comment by Tenischev** [comment]
@fmvilas Could be a solution, but by that you will introduce validation as part of main template code.
There are some drawbacks:
- more effort to keep messages unified
- keep all validation rules in mind during creation of new code

Usage of one dedicated hook is like having central error handler.

**Comment by fmvilas** [comment]
> more effort to keep messages unified

We can add a filter called `requireOperationId` at https://github.com/asyncapi/generator-filters. So the message is unified and the filter is available for every template.

> keep all validation rules in mind during creation of new code

You gotta keep them in mind anyway if you want to add them in a hook.

 ---

Another drawbacks of the hook solution:

1. We'll have to walk the whole document tree just to find some details. Performance on large documents will decrease a lot.
1. As the template evolves, we may end up validating stuff that's not needed anymore, just because we delete a part of the template but we forget to delete the validation in the hook.
1. For someone new who's reading the template, it's not clear that a validation is happening at template level.

Also, as a side comment, I don't think you need to make `operationId` required. You can generate one from the channel name + the operation name. It will not be ideal but provides a good default. You can then document in your README that `operationId` would allow users to customize those names. Same applies for Kafka and MQTT bindings. Try to provide defaults.

**Comment by Tenischev** [comment]
> We can add a filter called requireOperationId at https://github.com/asyncapi/generator-filters. 

If this case is relevant for several templates. Regarding this i suggested in Slack to add new parameter in `configuration` like `obligatoryFields`.

> You gotta keep them in mind anyway if you want to add them in a hook.

Not think so, if I miss it like a filter in a new code, I do not have any problem with generation. If I forget about hook validation, i receive error during test and find out about hook very easily because it one place for validation not smeared with a thin layer across template.

> We'll have to walk the whole document tree just to find some details. Performance on large documents will decrease a lot.

Hook receives already parsed AsyncAPI as an object. Actually in case of error it even will safe a time, because hook will be checked before the files generation.

>  we forget to delete the validation in the hook.

Or we forget to delete dedicated filter... But in case with hook you'll find it during testing.

> For someone new who's reading the template, it's not clear that a validation is happening at template level.

It's an issue for docs. Actually find some filter that could force stop process of generation in the middle could confuse even more.

---

Ofc some dummy default could be generated, but since AsyncAPI is declared for an application, I'm sure if you wrote AsyncAPI for a java application you would like to have good function names.

**Comment by derberg** [comment]
I think such functionality would make sense only as a core feature, as part of the configuration. It could be based on the same mechanism as `conditionalFiles`, using `JMESPath`. So you would just point what is required and then we throw proper unified error across templates.

regarding fallbacking `operationId`, sure you can fallback anything, but it should also be clear what is the recommended value. It should be described not manually in the readme but be part of configuration that is maintained, and readme generated.
